require:
  - rubocop-performance
  - rubocop-rails
  - rubocop-erb
  - rubocop-rspec
  - rubocop-rspec_rails
  - rubocop-factory_bot

AllCops:
  NewCops: enable

Style/Documentation:
  Enabled: false
