 production:
   periodic_cleanup:
     class: AdventSlackBotJob
     schedule: '*/20 * * * *'
#   periodic_command:
#     command: "SoftDeletedRecord.due.delete_all"
#     priority: 2
#     schedule: at 5am every day
